In [2]:
import pandas as pd
import numpy as np

In [3]:
df_confirm = pd.read_csv("time_series_covid19_confirmed_global.csv")
df_death = pd.read_csv("time_series_covid19_deaths_global.csv")

In [4]:
index_val = [("cse",2019),("cse",2020),("cse",2021),("cse",2022),("ece",2019),("ece",2020),("ece",2021),("ece",2022)]

In [7]:
a = pd.Series([1,2,3,4,5,6,7,8],index = index_val)
a

(cse, 2019)    1
(cse, 2020)    2
(cse, 2021)    3
(cse, 2022)    4
(ece, 2019)    5
(ece, 2020)    6
(ece, 2021)    7
(ece, 2022)    8
dtype: int64

```python
how to create multindex series ?
```

In [9]:
# multindexing is called hierarchical indexing
b = pd.MultiIndex.from_tuples(index_val)
b

MultiIndex([('cse', 2019),
            ('cse', 2020),
            ('cse', 2021),
            ('cse', 2022),
            ('ece', 2019),
            ('ece', 2020),
            ('ece', 2021),
            ('ece', 2022)],
           )

In [10]:
b.levels

FrozenList([['cse', 'ece'], [2019, 2020, 2021, 2022]])

In [11]:
b.levels[0]

Index(['cse', 'ece'], dtype='object')

In [13]:
c = pd.MultiIndex.from_product([['cse','ece'],[2019,2020,2021,2022]])
c

MultiIndex([('cse', 2019),
            ('cse', 2020),
            ('cse', 2021),
            ('cse', 2022),
            ('ece', 2019),
            ('ece', 2020),
            ('ece', 2021),
            ('ece', 2022)],
           )

In [29]:
multi = pd.Series([1,2,3,4,5,6,7,8],index = b)
multi

cse  2019    1
     2020    2
     2021    3
     2022    4
ece  2019    5
     2020    6
     2021    7
     2022    8
dtype: int64

In [30]:
multi[('cse',2022)]

4

In [31]:
multi['cse']

2019    1
2020    2
2021    3
2022    4
dtype: int64

### Unstack Functions converts a multiindex series into a dataframe

In [32]:
temp =multi.unstack()
temp

     2019  2020  2021  2022
cse     1     2     3     4
ece     5     6     7     8

### stack Functions converts a dataframe into a multiindex series

In [33]:
temp.stack()

cse  2019    1
     2020    2
     2021    3
     2022    4
ece  2019    5
     2020    6
     2021    7
     2022    8
dtype: int64

### But why do we use multindex because it helsp us to reduce the dimension of dataframe

#### Multindexing on basis of rows

In [38]:
branch_df1 = pd.DataFrame(
    [
        [1,2],
        [3,4],
        [5,6],
        [7,8],
        [9,10],
        [11,12],
        [13,14],
        [15,16],
    ],
    index = b ,columns=["avg package","salary in lpa"]
)

In [39]:
branch_df1

          avg package  salary in lpa
cse 2019            1              2
    2020            3              4
    2021            5              6
    2022            7              8
ece 2019            9             10
    2020           11             12
    2021           13             14
    2022           15             16

In [40]:
branch_df1.shape

(8, 2)

In [41]:
branch_df1.loc['cse']

      avg package  salary in lpa
2019            1              2
2020            3              4
2021            5              6
2022            7              8

In [42]:
branch_df1["avg package"]

cse  2019     1
     2020     3
     2021     5
     2022     7
ece  2019     9
     2020    11
     2021    13
     2022    15
Name: avg package, dtype: int64

#### Multindexing on basis of columns

In [52]:
branch_df2 = pd.DataFrame(
    [
        [1,2,0,0],
        [3,4,0,0],
        [5,6,0,0],
        [7,8,0,0],
    ],
    index = [2019,2020,2021,2022],
    columns= pd.MultiIndex.from_product([['delhi','mumbai'],["avg_packkage","students"]])
)

In [53]:
branch_df2
# 4d data represented in 2d

            delhi                mumbai
     avg_packkage students avg_packkage students
2019            1        2            0        0
2020            3        4            0        0
2021            5        6            0        0
2022            7        8            0        0

#### Multindexing on basis of cols and rows

In [55]:
branch_df3 = pd.DataFrame(
    [
        [1,2,0,0],
        [3,4,0,0],
        [5,6,0,0],
        [7,8,0,0],
        [9,10,0,0],
        [11,12,0,0],
        [13,14,0,0],
        [15,16,0,0]
    ],
    index = b,
    columns= pd.MultiIndex.from_product([['delhi','mumbai'],["avg_packkage","students"]])
)

In [56]:
branch_df3

                delhi                mumbai
         avg_packkage students avg_packkage students
cse 2019            1        2            0        0
    2020            3        4            0        0
    2021            5        6            0        0
    2022            7        8            0        0
ece 2019            9       10            0        0
    2020           11       12            0        0
    2021           13       14            0        0
    2022           15       16            0        0

### Stacking and unstacking